- job:
    name: ansible-role-carbon-base
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    post-run: tests/collect-logs.yaml
    roles:
      - zuul: openstack/ansible-role-carbon
      - zuul: openstack/ansible-role-whisper
    vars:
      # Default to python2 to make testing easier
      carbon_pip_extra_args: --install-option='--install-scripts=/usr/local/bin' --install-option='--install-lib=/usr/local/lib/python2.7/dist-packages' --install-option='--install-data=/usr/local/share/carbon'

# Testing for carbon_install_method: pip
- job:
    name: ansible-role-carbon
    parent: ansible-role-carbon-base

- job:
    name: ansible-role-carbon-fedora-latest
    parent: ansible-role-carbon
    nodeset: fedora-latest
    vars:
      carbon_pip_extra_args: --install-option='--install-scripts=/usr/local/bin' --install-option='--install-lib=/usr/lib/python2.7/site-packages' --install-option='--install-data=/usr/local/share/carbon'

- job:
    name: ansible-role-carbon-ubuntu-bionic
    parent: ansible-role-carbon
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-carbon-ubuntu-xenial
    parent: ansible-role-carbon
    nodeset: ubuntu-xenial

# Testing for carbon_install_method: git
- job:
    name: ansible-role-carbon-src
    parent: ansible-role-carbon-base
    vars:
      carbon_install_method: git
      whisper_install_method: git

- job:
    name: ansible-role-carbon-src-fedora-latest
    parent: ansible-role-carbon-src
    nodeset: fedora-latest
    vars:
      carbon_pip_extra_args: --install-option='--install-scripts=/usr/local/bin' --install-option='--install-lib=/usr/lib/python2.7/site-packages' --install-option='--install-data=/usr/local/share/carbon'

- job:
    name: ansible-role-carbon-src-ubuntu-bionic
    parent: ansible-role-carbon-src
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-carbon-src-ubuntu-xenial
    parent: ansible-role-carbon-src
    nodeset: ubuntu-xenial

- project:
    check:
      jobs:
        - ansible-role-carbon-fedora-latest
        - ansible-role-carbon-ubuntu-bionic
        - ansible-role-carbon-ubuntu-xenial
        - ansible-role-carbon-src-fedora-latest
        - ansible-role-carbon-src-ubuntu-bionic
        - ansible-role-carbon-src-ubuntu-xenial
        - tox-linters:
            required-projects:
              - openstack/ansible-role-whisper
            vars:
              tox_install_siblings: false
    gate:
      jobs:
        - ansible-role-carbon-fedora-latest
        - ansible-role-carbon-ubuntu-bionic
        - ansible-role-carbon-ubuntu-xenial
        - ansible-role-carbon-src-fedora-latest
        - ansible-role-carbon-src-ubuntu-bionic
        - ansible-role-carbon-src-ubuntu-xenial
        - tox-linters:
            required-projects:
              - openstack/ansible-role-whisper
            vars:
              tox_install_siblings: false
