- job:
    name: ansible-role-carbon-base
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    post-run: tests/collect-logs.yaml
    roles:
      - zuul: openstack/ansible-role-carbon
      - zuul: openstack/ansible-role-whisper

# Testing for carbon_install_method: pip
- job:
    name: ansible-role-carbon
    parent: ansible-role-carbon-base

- job:
    name: ansible-role-carbon-fedora-27
    parent: ansible-role-carbon
    nodeset: fedora-27

- job:
    name: ansible-role-carbon-ubuntu-bionic
    parent: ansible-role-carbon
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-carbon-ubuntu-xenial
    parent: ansible-role-carbon
    nodeset: ubuntu-xenial

# Testing for carbon_install_method: git
- job:
    name: ansible-role-carbon-src
    parent: ansible-role-carbon-base
    vars:
      carbon_install_method: git
      whisper_install_method: git

- job:
    name: ansible-role-carbon-src-fedora-27
    parent: ansible-role-carbon-src
    nodeset: fedora-27

- job:
    name: ansible-role-carbon-src-ubuntu-bionic
    parent: ansible-role-carbon-src
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-carbon-src-ubuntu-xenial
    parent: ansible-role-carbon-src
    nodeset: ubuntu-xenial

- project:
    check:
      jobs:
        - ansible-role-carbon-fedora-27
        - ansible-role-carbon-ubuntu-bionic
        - ansible-role-carbon-ubuntu-xenial
        - ansible-role-carbon-src-fedora-27
        - ansible-role-carbon-src-ubuntu-bionic
        - ansible-role-carbon-src-ubuntu-xenial
        - tox-linters
    gate:
      jobs:
        - ansible-role-carbon-fedora-27
        - ansible-role-carbon-ubuntu-xenial
        - ansible-role-carbon-src-fedora-27
        - ansible-role-carbon-src-ubuntu-xenial
        - tox-linters
